apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: { { .Values.namespace } }
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: { { .Values.frontend.service.port } }
  type: { { .Values.frontend.service.type } }
