apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: { { .Values.namespace } }
spec:
  replicas: { { .Values.frontend.replicaCount } }
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: { { .Values.frontend.service.port } }
